### ISSUE TITLE
README.md: Explain `rootDir`

### ISSUE THREAD

**Issue by ThomasLandauer** [phpstan/phpstan-symfony#101]
Since the path in the suggested `console-application.php` was wrong (see https://github.com/phpstan/phpstan-symfony/pull/100), I'm wondering if this is right:
```neon
container_xml_path: '%rootDir%/../../../var/cache/dev/srcApp_KernelDevDebugContainer.xml'
```
What is `%rootDir%` referring to? And/or how can I see what this path is ultimately resolved to?

**Comment by ondrejmirtes** [comment]
`%rootDir%` is mostly a PHPStan pre-0.12.x thing. Since 0.12, config paths are resolved based on where the current config file is.

Let's say you have `/foo/bar/phpstan.neon`. If you reference a path `baz/lorem.php` in that file, it will resolve to `/foo/bar/baz/lorem.php`.

I updated the README: https://github.com/phpstan/phpstan-symfony/commit/46cd7d5cc209651a3a7d7bbb18b213f6ec806e77
