### ISSUE TITLE
Add support for HeaderBag::all()

### ISSUE THREAD

**Issue by Seldaek** [phpstan/phpstan-symfony#264]
Since Symfony 5.4 all() has a generic return type defined which is nice, but sadly due to the $key arg it is very variable what you get back: https://github.com/symfony/symfony/blob/f5a8916bad0e45ef125d128dca6c2793bd0c55d2/src/Symfony/Component/HttpFoundation/HeaderBag.php#L66-L68

It'd be great if this extension supported all() like it does get(), switching to the correct return type based on $key being present or not.

**Comment by VincentLanglet** [comment]
Hi @Seldaek, since phpstan 1.6 this can be easily done with conditional return type I think 
https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types

The stub https://github.com/phpstan/phpstan-symfony/blob/1.2.x/stubs/Symfony/Component/HttpFoundation/HeaderBag.stub
need to be updated to add
```
@return $key is null ? array<string, array<int, string|null>> : array<int, string|null>
```

Do you want to provide the PR ?

**Comment by Seldaek** [comment]
True, opened https://github.com/symfony/symfony/pull/46613 thanks for the reminder
