### ISSUE TITLE
XML imports are not resolved

### ISSUE THREAD

**Issue by marcospassos** [phpstan/phpstan-symfony#38]
Currently, imports are not resolved:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services
        http://symfony.com/schema/dic/services/services-1.0.xsd">

    <imports>
        <import resource="foo.xml"/>
        <import resource="bar.xml"/>
    </imports>

</container>
```

**Comment by jvasseur** [comment]
This extension is supposed to receive the xml file dumped by Symfony that doesn't contains imports. What is your use case for resolving them ?

**Comment by marcospassos** [comment]
We use Symfony/DIC as a standalone library, so we don't have the debugging XML file, but the original files. I noticed that with small changes in the `XmlServiceMapFactory.php` is possible to add support for imports enabling the usage of the configuration files rather than dumped ones.

**Comment by jvasseur** [comment]
Using using the source files instead of the dumped is a bad idea because they don't represent the final state of the container since extensions and compiler pass (including the ones built-in the DIC component) can change the service definitions between the config and the final containers.

Instead you could use the `XmlDumper` to dump the xml representation of your compiled container at the same time you dump the corresponding PHP code.

**Comment by lookyman** [comment]
Solution provided by @jvasseur is the recommended one.
